/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.of.orange.county;

public class App {
    public String getGreeting() {
        return "Hello World NOOOO!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
